name: CI Pipeline

on:
  # Trigger on push to main
  push:
    branches:
      - main

  # Manual trigger for the workflow
  workflow_dispatch:


jobs:

  # =========================================================
  # Backend Tests
  # =========================================================
  backend-test:
    name: Test ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - service: user-service
            database: users
            port: 5433

          - service: student-service
            database: students
            port: 5434